--- 
- hosts: "{{ target | default('localhost') }}" 
  become: yes 
  roles: 
    # Installs openjdk-8-jdk
    - role: ansible-role-java
      install_type: "jdk"
      java_version: "default"
      java_home: False
    - jenkins 
    - nodejs 
